#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '23':
        pose: /mavros/mocap/pose
        pose2d: Robot_1/ground_pose
        child_frame_id: base_link
        parent_frame_id: map

optitrack_config:
        multicast_address: 224.0.0.1
